[package]
name = "cpm"
version = "0.1.0"
authors = [ "Ross Hadden <rosshadden@gmail.com>" ]
description = "Cosmic Package Manager"
repository = "http://github.com/rosshadden/cpm"
keywords = [ "cosmic", "package manager", "universal", "language-agnostic" ]

[actions]
foo = "echo foo!"
run = "echo run run run"
